// generated by stringer -type=Player; DO NOT EDIT

package game

import "fmt"

const _Player_name = "Player1Player2"

var _Player_index = [...]uint8{0, 7, 14}

func (i Player) String() string {
	if i < 0 || i >= Player(len(_Player_index)-1) {
		return fmt.Sprintf("Player(%d)", i)
	}
	return _Player_name[_Player_index[i]:_Player_index[i+1]]
}
