// generated by stringer -type=MsgType; DO NOT EDIT

package protocol

import "fmt"

const _MsgType_name = "PingConnectConnectionReplyRequestOpenGamesListSendOpenGamesListCreateGameJoinGameGamePreGameStatusAcceptGameRejectGameGameStateGameSetPieceGameMoveAbandonGameChatMessageGenericResultGameWonGameLost"

var _MsgType_index = [...]uint8{0, 4, 11, 26, 46, 63, 73, 81, 98, 108, 118, 127, 139, 147, 158, 169, 182, 189, 197}

func (i MsgType) String() string {
	if i >= MsgType(len(_MsgType_index)-1) {
		return fmt.Sprintf("MsgType(%d)", i)
	}
	return _MsgType_name[_MsgType_index[i]:_MsgType_index[i+1]]
}
